spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: qian0816
logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG
